import Navbar from "../components/Navbar"
import Switchbar from "../components/Switchbar"
import { AssetTable } from "../components/Table"
import Popup from '../pages/Popup';
import { useState } from 'react';

export default function Trailers(){
    const [isOpen, setIsOpen] = useState(false);

    const togglePopup = () => {
      setIsOpen(!isOpen);
    }
    return (
    <div>
    <Navbar/>
    <Switchbar/>
    <div className="tableSection">
    <AssetTable
        assets={[
          { id: 1,
            type: 'Trailer',
            asset: 'S211',
            location: 'Pleasanton',
            status: 'IN-SERVICE',
            date: '12/07/22',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 2,
            type: 'Trailer',
            asset: 'S212',
            location: 'Pleasanton',
            status: 'OUT-OF-SERVICE',
            date: '12/05/2022',
            employee: '',
            notes: 'Radiator Broken',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 3,
            type: 'Trailer',
            asset: 'S214',
            location: 'Pleasanton',
            status: 'OUT-OF-SERVICE',
            date: '12/05/2022',
            employee: '',
            notes: 'Crack in Windshield',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 4,
            type: 'Trailer',
            asset: 'S215',
            location: 'Pleasanton',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 5,
            type: 'Trailer',
            asset: 'S216',
            location: 'Pleasanton',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 6,
            type: 'Trailer',
            asset: 'S217',
            location: 'Pleasanton',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 7,
            type: 'Trailer',
            asset: 'S218',
            location: 'Pleasanton',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 8,
            type: 'Trailer',
            asset: 'G3272',
            location: 'ZT',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 9,
            type: 'Trailer',
            asset: 'G3273',
            location: 'ZT',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 10,
            type: 'Trailer',
            asset: 'G3274',
            location: 'ZT',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 11,
            type: 'Trailer',
            asset: 'G3275',
            location: 'ZT',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 12,
            type: 'Trailer',
            asset: 'G3276',
            location: 'ZT',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 13,
            type: 'Trailer',
            asset: 'G3277',
            location: 'ZT',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 14,
            type: 'Trailer',
            asset: 'G3278',
            location: 'ZT',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 15,
            type: 'Trailer',
            asset: 'G3279',
            location: 'ZT',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 16,
            type: 'Trailer',
            asset: 'G3280',
            location: 'ZT',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 17,
            type: 'Trailer',
            asset: 'G3281',
            location: 'ZT',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 22,
            type: 'Trailer',
            asset: 'S519',
            location: 'ZT',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 23,
            type: 'Trailer',
            asset: 'S520',
            location: 'Kermit',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 24,
            type: 'Trailer',
            asset: 'S521',
            location: 'Kermit',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 25,
            type: 'Trailer',
            asset: 'S522',
            location: 'Kermit',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 26,
            type: 'Trailer',
            asset: 'S523',
            location: 'Kermit',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 27,
            type: 'Trailer',
            asset: 'S524',
            location: 'Kermit',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 28,
            type: 'Trailer',
            asset: 'S525',
            location: 'Kermit',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 29,
            type: 'Trailer',
            asset: 'S526',
            location: 'ZT',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 30,
            type: 'Trailer',
            asset: 'S527',
            location: 'Kermit',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 31,
            type: 'Trailer',
            asset: 'S528',
            location: 'Kermit',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 32,
            type: 'Trailer',
            asset: 'S529',
            location: 'ZT',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 33,
            type: 'Trailer',
            asset: 'S530',
            location: 'Kermit',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 47,
            type: 'Trailer',
            asset: 'S832',
            location: 'Pleasanton',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 48,
            type: 'Trailer',
            asset: 'S833',
            location: 'ZT',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 49,
            type: 'Trailer',
            asset: 'S834',
            location: 'ZT',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 50,
            type: 'Trailer',
            asset: 'S835',
            location: 'Kermit',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 51,
            type: 'Trailer',
            asset: 'S836',
            location: 'Pleasanton',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 52,
            type: 'Trailer',
            asset: 'S837',
            location: 'ZT',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 53,
            type: 'Trailer',
            asset: 'S838',
            location: 'ZT',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 54,
            type: 'Trailer',
            asset: 'S839',
            location: 'Kermit',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 55,
            type: 'Trailer',
            asset: 'S840',
            location: 'Kermit',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 56,
            type: 'Trailer',
            asset: 'S841',
            location: 'Kermit',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 60,
            type: 'Trailer',
            asset: 'S842',
            location: 'Kermit',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 61,
            type: 'Trailer',
            asset: 'S843',
            location: 'Kermit',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 62,
            type: 'Trailer',
            asset: 'S844',
            location: 'Pleasanton',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 63,
            type: 'Trailer',
            asset: 'S845',
            location: 'ZT',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 64,
            type: 'Trailer',
            asset: 'S846',
            location: 'Kermit',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 65,
            type: 'Trailer',
            asset: 'S847',
            location: 'Kermit',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 66,
            type: 'Trailer',
            asset: 'S848',
            location: 'Kermit',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 67,
            type: 'Trailer',
            asset: 'S849',
            location: 'Kermit',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 68,
            type: 'Trailer',
            asset: 'S850',
            location: 'Kermit',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 69,
            type: 'Trailer',
            asset: 'S851',
            location: 'Kermit',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 96,
            type: 'Trailer',
            asset: 'S873',
            location: 'Kermit',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 97,
            type: 'Trailer',
            asset: 'S874',
            location: 'Kermit',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 98,
            type: 'Trailer',
            asset: 'S875',
            location: 'Kermit',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 99,
            type: 'Trailer',
            asset: 'S876',
            location: 'Kermit',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 100,
            type: 'Trailer',
            asset: 'S877',
            location: 'Kermit',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 101,
            type: 'Trailer',
            asset: 'S878',
            location: 'Kermit',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 102,
            type: 'Trailer',
            asset: 'S879',
            location: 'Kermit',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 103,
            type: 'Trailer',
            asset: 'S880',
            location: 'Kermit',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 104,
            type: 'Trailer',
            asset: 'S881',
            location: 'Kermit',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 105,
            type: 'Trailer',
            asset: 'S882',
            location: 'Kermit',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 106,
            type: 'Trailer',
            asset: 'S883',
            location: 'Kermit',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 107,
            type: 'Trailer',
            asset: 'S884',
            location: 'Kermit',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 108,
            type: 'Trailer',
            asset: 'S885',
            location: 'Kermit',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 109,
            type: 'Trailer',
            asset: 'S886',
            location: 'Kermit',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
          { id: 110,
            type: 'Trailer',
            asset: 'S887',
            location: 'Kermit',
            status: 'IN-SERVICE',
            date: '',
            employee: '',
            notes: '',
            modify: <input type="button" value="update" onClick={togglePopup}
          /> },
        ]}
      />
       {isOpen && <Popup handleClose={togglePopup}/>}
       </div>
    </div>
    )
}